Repository NREL/OpenStudio-HPXML-Calibration, pull requests merged in 2025-10, with the labels that each got.

#115 Add search algorithm configuration documentation
  docs/search_config.md
Labels: documentation

#34 Documentation site
  .github/workflows/docs.yml
  .markdownlint.json
  .pre-commit-config.yaml
  README.md
  docs/bpi2400.md
  docs/code_documentation/calibrate.md
  docs/code_documentation/hpxml.md
  docs/code_documentation/weather_normalization/degree_days.md
  docs/code_documentation/weather_normalization/inverse_model.md
  docs/code_documentation/weather_normalization/regression.md
  docs/code_documentation/weather_normalization/utility_data.md
  docs/index.md
  docs/inputs.md
  docs/search_config.md
  mkdocs.yml
  pyproject.toml
  src/openstudio_hpxml_calibration/__init__.py
  src/openstudio_hpxml_calibration/calibrate.py
  src/openstudio_hpxml_calibration/hpxml.py
  src/openstudio_hpxml_calibration/utils.py
  src/openstudio_hpxml_calibration/weather_normalization/degree_days.py
  src/openstudio_hpxml_calibration/weather_normalization/inverse_model.py
  src/openstudio_hpxml_calibration/weather_normalization/regression.py
  tests/test_calibrate.py
  tests/test_weather_normalization.py
  uv.lock
Labels: enhancement

#118 Fix Action version in docs workflow
  .github/workflows/docs.yml
Labels: bug
